export const PROVINCE_DATA = [
    {
        code: 'ab',
        name: 'Alberta',
    },
    {
        code: 'bc',
        name: 'British Columbia',
    },
    {
        code: 'mb',
        name: 'Manitoba',
    },
    {
        code: 'nb',
        name: 'New Brunswick',
    },
    {
        code: 'nl',
        name: 'Newfoundland and Labrador',
    },
    {
        code: 'nt',
        name: 'Northwest Territories',
    },
    {
        code: 'ns',
        name: 'Nova Scotia',
    },
    {
        code: 'nu',
        name: 'Nunavut',
    },
    {
        code: 'on',
        name: 'Ontario',
    },
    {
        code: 'pe',
        name: 'Prince Edward Island',
    },
    {
        code: 'qc',
        name: 'Quebec',
    },
    {
        code: 'sk',
        name: 'Saskatchewan',
    },
    {
        code: 'yt',
        name: 'Yukon',
    },
]

export const COMPANY_NAME = 'Co-Foundation'

export const DEFAULT_PROVINCE = 'on'

export const AVAILABLE_PROVINCES = ['ab', 'bc', 'on']

export const FORM_FIELDS = {
    '07200': {
        '1.type': 'bus_corp1',
        '2.corpNumber': 'corp_num',
        '3.corpAnniversary.year': 'year_1',
        '3.corpAnniversary.month': 'month_1',
        '3.corpAnniversary.day': 'day_1',
        '4.corpName1': 'corpname.0',
        '4.corpName2': 'corpname.1',
        '4.corpName3': 'corpname.2',
        '4.corpName4': 'corpname.3',
        '5.office.careOf': 'address_of_registered',
        '5.office.streetNum': 'street_no',
        '5.office.streetName': 'street_name',
        '5.office.suite': 'suite',
        '5.office.street2': 'street_name2',
        '5.office.city': 'Text15',
        '5.office.postalCode': 'p_code1',
        '6.mailing.checkSame': 'addr_check',
        '6.mailing.streetNum': 'mailaddr_street_no',
        '6.mailing.streetName': 'mailaddr_street_name',
        '6.mailing.suite': 'mailaddr_suite`',
        '6.mailing.street2': 'mailaddr_street_name2',
        '6.mailing.city': 'mailaddr_city',
        '6.mailing.province': 'mailaddr_province`',
        '6.mailing.country': 'mailaddr_country',
        '6.mailing.postalCode': 'mailaddr_pcode',
        '7.language': 'lang_pref',
        '8.numberOfSchedAPages': 'Text27',
        '9.authorization.name': 'authorizing_name',
        '9.authorization.role': 'signee',
        'A.corpNumber': 'OCN_2',
        'A.corpAnniversary.year': 'year_2',
        'A.corpAnniversary.month': 'month_2',
        'A.corpAnniversary.day': 'day_2',
        'A.director1.lastName': 'director_info_lastname',
        'A.director1.firstName': 'director_info_firstname',
        'A.director1.midName': 'director_info_middlename',
        'A.director1.streetNum': 'director_info_streetNum',
        'A.director1.suite': 'director_info_suite',
        'A.director1.streetName': 'director_info_streetName',
        'A.director1.street2': 'director_info_streetName_cont',
        'A.director1.city': 'director_info_city',
        'A.director1.province': 'director_info_province',
        'A.director1.country': 'director_info_country',
        'A.director1.postalCode': 'director_info_pcode',
        'A.director1.isCanadian': 'canadian_resident',
        'A.director1.director.startYear': 'year_3',
        'A.director1.director.startMonth': 'month_3',
        'A.director1.director.startDay': 'day_3',
        'A.director1.director.endYear': 'year_4',
        'A.director1.director.endMonth': 'month_4',
        'A.director1.director.endDay': 'day_4',
        'A.director1.president.startYear': 'year_5.0.0',
        'A.director1.secretary.startYear': 'year_5.0.1',
        'A.director1.treasurer.startYear': 'year_5.0.2',
        'A.director1.gm.startYear': 'year_5.0.3',
        'A.director1.other.startYear': 'year_5.0.4',
        'A.director1.president.endYear': 'year_5.1.0',
        'A.director1.secretary.endYear': 'year_5.1.1',
        'A.director1.treasurer.endYear': 'year_5.1.2',
        'A.director1.gm.endYear': 'year_5.1.3',
        'A.director1.other.endYear': 'year_5.1.4',
        'A.director1.president.startMonth': 'month_5.0.0',
        'A.director1.secretary.startMonth': 'month_5.0.1',
        'A.director1.treasurer.startMonth': 'month_5.0.2',
        'A.director1.gm.startMonth': 'month_5.0.3',
        'A.director1.other.startMonth': 'month_5.0.4',
        'A.director1.president.endMonth': 'month_5.1.0',
        'A.director1.secretary.endMonth': 'month_5.1.1',
        'A.director1.treasurer.endMonth': 'month_5.1.2',
        'A.director1.gm.endMonth': 'month_5.1.3',
        'A.director1.other.endMonth': 'month_5.1.4',
        'A.director1.president.startDay': 'day_5.0.0',
        'A.director1.secretary.startDay': 'day_5.0.1',
        'A.director1.treasurer.startDay': 'day_5.0.2',
        'A.director1.gm.startDay': 'day_5.0.3',
        'A.director1.other.startDay': 'day_5.0.4',
        'A.director1.president.endDay': 'day_5.1.0',
        'A.director1.secretary.endDay': 'day_5.1.1',
        'A.director1.treasurer.endDay': 'day_5.1.2',
        'A.director1.gm.endDay': 'day_5.1.3',
        'A.director1.other.endDay': 'day_5.1.4',
        'A.director1.other.title': 'other_title',
        'A.director2.lastName': 'director_info_lastname2',
        'A.director2.firstName': 'director_info_firstname2',
        'A.director2.midName': 'director_info_middlename2',
        'A.director2.streetNum': 'director_info_streetNum2',
        'A.director2.suite': 'director_info_suite2',
        'A.director2.streetName': 'director_info_streetName2',
        'A.director2.street2': 'director_info_streetName2_cont',
        'A.director2.city': 'director_info_city2',
        'A.director2.province': 'director_info_province2',
        'A.director2.country': 'director_info_country2',
        'A.director2.postalCode': 'director_info_pcode2',
        'A.director2.isCanadian': 'canadian_resident2',
        'A.director2.director.startYear': 'year_6',
        'A.director2.director.startMonth': 'month_6',
        'A.director2.director.startDay': 'day_6',
        'A.director2.director.endYear': 'year_7',
        'A.director2.director.endMonth': 'month_7',
        'A.director2.director.endDay': 'day_7',
        'A.director2.president.startYear': 'year_8.0.0',
        'A.director2.secretary.startYear': 'year_8.0.1',
        'A.director2.treasurer.startYear': 'year_8.0.2',
        'A.director2.gm.startYear': 'year_8.0.3',
        'A.director2.other.startYear': 'year_8.0.4',
        'A.director2.president.endYear': 'year_8.1.0',
        'A.director2.secretary.endYear': 'year_8.1.1',
        'A.director2.treasurer.endYear': 'year_8.1.2',
        'A.director2.gm.endYear': 'year_8.1.3',
        'A.director2.other.endYear': 'year_8.1.4',
        'A.director2.president.startMonth': 'month_8.0.0',
        'A.director2.secretary.startMonth': 'month_8.0.1',
        'A.director2.treasurer.startMonth': 'month_8.0.2',
        'A.director2.gm.startMonth': 'month_8.0.3',
        'A.director2.other.startMonth': 'month_8.0.4',
        'A.director2.president.endMonth': 'month_8.1.0',
        'A.director2.secretary.endMonth': 'month_8.1.1',
        'A.director2.treasurer.endMonth': 'month_8.1.2',
        'A.director2.gm.endMonth': 'month_8.1.3',
        'A.director2.other.endMonth': 'month_8.1.4',
        'A.director2.president.startDay': 'day_8.0.0',
        'A.director2.secretary.startDay': 'day_8.0.1',
        'A.director2.treasurer.startDay': 'day_8.0.2',
        'A.director2.gm.startDay': 'day_8.0.3',
        'A.director2.other.startDay': 'day_8.0.4',
        'A.director2.president.endDay': 'day_8.1.0',
        'A.director2.secretary.endDay': 'day_8.1.1',
        'A.director2.treasurer.endDay': 'day_8.1.2',
        'A.director2.gm.endDay': 'day_8.1.3',
        'A.director2.other.endDay': 'day_8.1.4',
        'A.director2.other.title': 'other_title2',
    }
}
